baseURL = 'https://jpwiig.github.io/d.it-i-o-hugo/'
languageCode = 'no-nb'
title = 'D.IT-I/O - Linjeforeningen ved insitutt IT'
theme = 'risotto'

[[menu.main]]
identifier = "about"
name = "om foreningen"
url = "about"


[caches]
  [caches.images]
    dir = ':cacheDir/images'