baseURL = 'http://example.org'
languageCode = 'no-nb'
title = 'D.IT-I/O - Linjeforeningen ved insitutt IT'
theme = 'risotto'

[[menu.main]]
identifier = "about"
name = "om foreningen"
url = "about"

[[menu.main]]
identifier = "events"
name = "Hendelser:"
url = "events"


[[menu.main]]
identifier = "vedtekter"
name = "Foreningens grunnlag"
url = "vedtekter"


[caches]
  [caches.images]
    dir = ':cacheDir/images'
